from pathlib import Path
import pytest

from odoo_typegen.compiler.consolidated_model import (
    ConsolidatedModel,
    StubAttribute,
    StubClass,
    StubMethod,
)
from odoo_typegen.emitter.type_emitter import TypeEmitter


@pytest.fixture(name="consolidated_models")
def fixture_models():
    return (
        ConsolidatedModel(
            name="crm.lead",
            stub_class=StubClass(
                import_path="crm.lead",
                class_name="CrmLead",
                bases=("odoo.models.Model",),
                attributes=(
                    StubAttribute(
                        name="x_base_code",
                        type="str",
                        module="crm_base_extension",
                        file=Path("crm_base_extension/models/crm_lead.py"),
                        line=7,
                    ),
                    StubAttribute(
                        name="x_is_priority",
                        type="bool",
                        module="crm_base_extension",
                        file=Path("crm_base_extension/models/crm_lead.py"),
                        line=8,
                    ),
                ),
                methods=(
                    StubMethod(
                        name="action_mark_priority",
                        signature="def action_mark_priority(self) -> None",
                        module="crm_base_extension",
                        file=Path("crm_base_extension/models/crm_lead.py"),
                        line=10,
                    ),
                ),
            ),
        ),
    )


def test_type_emitter_generates_pyi_files(tmp_path, consolidated_models):
    emitted_files = TypeEmitter(output_path=tmp_path).emit(consolidated_models)

    assert emitted_files == (tmp_path / "crm/lead.pyi",)
    assert (tmp_path / "crm/lead.pyi").read_text() == (
        "# Generated by odoo-typegen.\n"
        "from odoo.models import Model\n"
        "\n"
        "\n"
        "class CrmLead(Model):\n"
        "    x_base_code: str\n"
        "    x_is_priority: bool\n"
        "    def action_mark_priority(self) -> None: ...\n"
    )


def test_emitter_emits_environment_pyi_file(tmp_path, consolidated_models):
    environment = StubClass(
        import_path="odoo.orm.environments",
        class_name="Environment",
        imports=("import typing", "from crm.lead import CrmLead"),
        attributes=(StubAttribute(name="uid", type="int"),),
        methods=(
            StubMethod(
                name="__getitem__",
                decorators=("@typing.overload",),
                signature=(
                    "def __getitem__(self, "
                    'model_name: typing.Literal["crm.lead"]) -> CrmLead'
                ),
            ),
            StubMethod(
                name="__getitem__",
                decorators=("@typing.overload",),
                signature="def __getitem__(self, model_name: str) -> typing.Any",
            ),
        ),
    )

    emitted_files = TypeEmitter(output_path=tmp_path).emit_environment(environment)

    assert emitted_files == (
        tmp_path / "odoo/orm/environments.pyi",
        tmp_path / "odoo/api/__init__.pyi",
    )
    assert (tmp_path / "odoo/orm/environments.pyi").read_text() == (
        "# Generated by odoo-typegen.\n"
        "import typing\n"
        "from crm.lead import CrmLead\n"
        "\n"
        "\n"
        "class Environment:\n"
        "    uid: int\n"
        "    @typing.overload\n"
        "    def __getitem__(self, model_name: typing.Literal[\"crm.lead\"]) -> CrmLead: ...\n"
        "    @typing.overload\n"
        "    def __getitem__(self, model_name: str) -> typing.Any: ...\n"
    )
    assert (tmp_path / "odoo/api/__init__.pyi").read_text() == (
        "from odoo.orm.environments import Environment as Environment\n"
    )


def test_emitter_emits_core_model_pyi_files(tmp_path):
    core_models = (
        StubClass(
            import_path="odoo.orm.models",
            class_name="BaseModel",
            imports=("import typing", "from odoo.orm.environments import Environment"),
            attributes=(
                StubAttribute(name="env", type="Environment"),
                StubAttribute(name="display_name", type="str"),
            ),
            methods=(
                StubMethod(
                    name="browse",
                    signature="def browse(self, ids: typing.Any) -> typing.Any",
                ),
            ),
        ),
        StubClass(
            import_path="odoo.orm.models",
            class_name="Model",
            imports=("import typing",),
            bases=("odoo.orm.models.BaseModel",),
            attributes=(
                StubAttribute(name="_auto", type="bool"),
            ),
        ),
    )

    emitted_files = TypeEmitter(output_path=tmp_path).emit_core_models(core_models)

    assert emitted_files == (
        tmp_path / "odoo/orm/models.pyi",
        tmp_path / "odoo/models/__init__.pyi",
    )
    assert (tmp_path / "odoo/orm/models.pyi").read_text() == (
        "# Generated by odoo-typegen.\n"
        "import typing\n"
        "from odoo.orm.environments import Environment\n"
        "\n"
        "\n"
        "class BaseModel:\n"
        "    env: Environment\n"
        "    display_name: str\n"
        "    def browse(self, ids: typing.Any) -> typing.Any: ...\n"
        "\n"
        "class Model(BaseModel):\n"
        "    _auto: bool\n"
    )
    assert (tmp_path / "odoo/models/__init__.pyi").read_text() == (
        "from odoo.orm.models import BaseModel as BaseModel\n"
        "from odoo.orm.models import Model as Model\n"
    )
