from pathlib import Path

import pytest

from odoo_typegen.cli import _generate, app


@pytest.mark.parametrize("arguments", [[], ["generate"]])
def test_cli_defaults_output_path_to_typings(tmp_path, monkeypatch, arguments):
    addon_path = Path(__file__).resolve().parents[3] / "tests/test_addons"
    monkeypatch.chdir(tmp_path)

    with pytest.raises(SystemExit) as exit_info:
        app([*arguments, str(addon_path)])

    assert exit_info.value.code == 0
    assert (tmp_path / "typings/crm/lead.pyi").is_file()
    assert (tmp_path / "typings/odoo/orm/environments.pyi").is_file()


def test_generate_emits_model_environment_and_base_model_stubs(tmp_path, capsys):
    addon_path = Path(__file__).resolve().parents[3] / "tests/test_addons"

    emitted_files = _generate(
        addon_path=addon_path,
        output_path=tmp_path,
    )

    assert emitted_files == (
        tmp_path / "crm/lead.pyi",
        tmp_path / "odoo/orm/environments.pyi",
        tmp_path / "odoo/api/__init__.pyi",
        tmp_path / "odoo/orm/models.pyi",
        tmp_path / "odoo/models/__init__.pyi",
    )
    assert (tmp_path / "crm/lead.pyi").read_text().startswith(
        "# Generated by odoo-typegen.\n"
        "from odoo.models import Model\n"
        "\n"
        "\n"
        "class CrmLead(Model):\n"
    )
    assert 'model_name: typing.Literal["crm.lead"]' in (
        tmp_path / "odoo/orm/environments.pyi"
    ).read_text()
    assert (tmp_path / "odoo/api/__init__.pyi").read_text() == (
        "from odoo.orm.environments import Environment as Environment\n"
    )
    core_model_stubs = (tmp_path / "odoo/orm/models.pyi").read_text()
    assert "env: Environment" in core_model_stubs
    assert "class Model(BaseModel):" in core_model_stubs
    assert (tmp_path / "odoo/models/__init__.pyi").read_text() == (
        "from odoo.orm.models import BaseModel as BaseModel\n"
        "from odoo.orm.models import Model as Model\n"
    )

    printed_files = tuple(
        Path(line)
        for line in capsys.readouterr().out.splitlines()
    )
    assert printed_files == emitted_files


def test_generate_with_odoo_path_prints_environment_reexport(tmp_path, capsys):
    addon_path = Path(__file__).resolve().parents[3] / "tests/test_addons"
    odoo_path = tmp_path / "odoo-source"
    environment_source = odoo_path / "odoo/orm/environments.py"
    environment_source.parent.mkdir(parents=True)
    environment_source.write_text(
        "class Environment:\n"
        "    uid: int\n"
        "    def is_superuser(self) -> bool:\n"
        "        ...\n"
    )

    emitted_files = _generate(
        addon_path=addon_path,
        output_path=tmp_path / "typings",
        odoo_path=odoo_path,
    )

    assert emitted_files == (
        tmp_path / "typings/crm/lead.pyi",
        tmp_path / "typings/odoo/orm/environments.pyi",
        tmp_path / "typings/odoo/api/__init__.pyi",
        tmp_path / "typings/odoo/orm/models.pyi",
        tmp_path / "typings/odoo/models/__init__.pyi",
    )
    assert (tmp_path / "typings/odoo/api/__init__.pyi").read_text() == (
        "from odoo.orm.environments import Environment as Environment\n"
    )
    assert "uid: int" in (
        tmp_path / "typings/odoo/orm/environments.pyi"
    ).read_text()
    assert "def is_superuser(self) -> bool: ..." in (
        tmp_path / "typings/odoo/orm/environments.pyi"
    ).read_text()

    printed_files = tuple(
        Path(line)
        for line in capsys.readouterr().out.splitlines()
    )
    assert printed_files == emitted_files
