from pathlib import Path

from odoo_typegen.compiler.consolidated_model import ConsolidatedModel, StubClass


class TypeEmitter:
    def __init__(self, output_path: Path):
        self._output_path = output_path

    def emit(self, models: tuple[ConsolidatedModel, ...]) -> tuple[Path, ...]:
        emitted_files: list[Path] = []

        for model in models:
            output_file = self._output_file_for_model(model.name)
            output_file.parent.mkdir(parents=True, exist_ok=True)
            output_file.write_text(
                self._render_stub_class(model.stub_class),
            )
            emitted_files.append(output_file)

        return tuple(emitted_files)

    def _output_file_for_model(self, model_name: str) -> Path:
        return self._output_path.joinpath(*model_name.split(".")).with_suffix(".pyi")

    def emit_core_models(self, models: tuple[StubClass, ...]) -> tuple[Path, ...]:
        implementation_file = self._output_path / "odoo/orm/models.pyi"
        implementation_file.parent.mkdir(parents=True, exist_ok=True)
        implementation_file.write_text(self._render_stub_classes(models))

        public_file = self._output_path / "odoo/models/__init__.pyi"
        public_file.parent.mkdir(parents=True, exist_ok=True)
        public_file.write_text(
            "".join(
                f"from odoo.orm.models import {model.class_name} as {model.class_name}\n"
                for model in models
            )
        )

        return (implementation_file, public_file)

    def emit_environment(self, environment: StubClass) -> tuple[Path, ...]:
        implementation_file = self._output_path / "odoo/orm/environments.pyi"
        implementation_file.parent.mkdir(parents=True, exist_ok=True)
        implementation_file.write_text(self._render_stub_class(environment))

        public_file = self._output_path / "odoo/api/__init__.pyi"
        public_file.parent.mkdir(parents=True, exist_ok=True)
        public_file.write_text(
            "from odoo.orm.environments import Environment as Environment\n"
        )

        return (implementation_file, public_file)

    def _render_stub_class(self, stub_class: StubClass) -> str:
        return "\n".join(
            (
                *self._render_stub_class_lines(stub_class),
                "",
            )
        )

    def _render_stub_classes(self, stub_classes: tuple[StubClass, ...]) -> str:
        imports: list[str] = []
        class_blocks: list[list[str]] = []
        for stub_class in stub_classes:
            imports.extend(self._render_imports(stub_class))
            class_blocks.append(self._render_stub_class_body_lines(stub_class))

        lines = [
            "# Generated by odoo-typegen.",
            *tuple(dict.fromkeys(imports)),
            "",
            "",
        ]
        for index, class_block in enumerate(class_blocks):
            if index > 0:
                lines.append("")
            lines.extend(class_block)
        lines.append("")
        return "\n".join(lines)

    def _render_stub_class_lines(self, stub_class: StubClass) -> tuple[str, ...]:
        return (
            "# Generated by odoo-typegen.",
            *self._render_imports(stub_class),
            "",
            "",
            *self._render_stub_class_body_lines(stub_class),
        )

    def _render_stub_class_body_lines(self, stub_class: StubClass) -> list[str]:
        members = [
            f"    {attribute.name}: {attribute.type}"
            for attribute in stub_class.attributes
        ]
        for method in stub_class.methods:
            members.extend(f"    {decorator}" for decorator in method.decorators)
            members.append(f"    {method.signature}: ...")

        if not members:
            members = ["    ..."]

        bases = self._render_bases(stub_class)

        return [
            f"class {stub_class.class_name}{bases}:",
            *members,
        ]

    @staticmethod
    def _render_imports(stub_class: StubClass) -> tuple[str, ...]:
        imports = list(stub_class.imports)
        for base in stub_class.bases:
            if "." not in base:
                continue

            module, class_name = base.rsplit(".", 1)
            if module == stub_class.import_path:
                continue
            imports.append(f"from {module} import {class_name}")

        return tuple(dict.fromkeys(imports))

    @staticmethod
    def _render_bases(stub_class: StubClass) -> str:
        if not stub_class.bases:
            return ""

        base_names = [
            base.rsplit(".", 1)[-1]
            for base in stub_class.bases
        ]
        return f"({', '.join(base_names)})"
